[package]
name = "fido2-rs"
version = "0.1.0"
edition = "2021"


[dependencies]
thiserror = "1.0.37"
bitflags = "1.3.2"
libfido2-sys = { version = "0.1.0", path = "../libfido2-sys" }

[dev-dependencies]
anyhow = "1.0.66"